image: node:6

basic_test:
  script:
   - npm --version
   - npm install
   - npm test

downstream:
  script:
   - npm install
   - npm run compile
   - npm run downstream

test_262:
  script:
   - npm install
   - npm run compile
   - npm run test-262
